[package]
name = "video-rotator"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
ffmpeg-next = { version = "8.0.0", features = ["build", "build-lib-x264", "build-license-gpl"] }
rfd = "0.15.4"
slint = "1.13.1"

[build-dependencies]
slint-build = "1.13.1"
