---

on: [push]

name: Build rust application for Windows

jobs:
  build-app:
    name: release ${{ matrix.target }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            archive: zip
    steps:
      - uses: actions/checkout@master

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rust-src
          targets: "${{ matrix.target }}"

      - name: Build Binary
        run: cargo build --verbose --release --target-dir ./target --target ${{ matrix.target }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Binary
          path: ./target/${{ matrix.target }}
